@startuml

[*] -> plugins.txt

plugins.txt : file exists
plugins.txt --> sha256_I : yes
plugins.txt -> [*] : no

state "plugins.sha256 (I)" as sha256_I : file exists
sha256_I -> sha256_II : yes
sha256_I -> install : no

state "plugins.sha256 (II)" as sha256_II : sha256 of 'plugins.txt' ok
sha256_II --> force : yes
sha256_II -> install : no

state "Force update?" as force : forcePluginUpdates == true
force --> install : yes
force -> [*] : no

install : install/update plugins
install --> sha256_III

state "plugins.sha256 (III)" as sha256_III : write checksum file
sha256_III --> [*]

@enduml
