{{- if .Values.keycloak.x509.enabled -}}
{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-x509
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
data:
{{- with .Values.keycloak.x509.certificates }}
  {{- toYaml . | nindent 2 }}
{{- end -}}
{{- end -}}
