{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-sh
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
data:
  keycloak.sh: |
    #!/usr/bin/env bash

    set -o errexit
    set -o nounset

    if [ -d /plugins ]; then
      mkdir -p /opt/jboss/keycloak/standalone/deployments
      cp -au /plugins/* /opt/jboss/keycloak/standalone/deployments || :
    fi

    exec /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 {{ .Values.keycloak.extraArgs }}{{- if $highAvailability }} -c standalone-ha.xml{{ else }} -c standalone.xml{{ end }}
