{{- with .Values.prometheusOperator.prometheusRule -}}
{{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "keycloak.fullname" $ }}
  {{- with .annotations }}
  annotations:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
  {{- with .labels }}
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "keycloak.fullname" $ }}
      rules:
        {{- toYaml .rules | nindent 8 }}
{{- end }}
{{- end -}}
