{{- if and (not .Values.keycloak.existingSecret) (not .Values.keycloak.password_file) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.passwordKey" . }}: {{ include "keycloak.password" . }}
{{- end}}
