{{- if not .Values.keycloak.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.keycloak.password }}
  {{ .Values.keycloak.existingSecretKey }}: {{ .Values.keycloak.password | b64enc | quote }}
{{- else }}
  {{ .Values.keycloak.existingSecretKey }}: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- end}}
