{{- if .Values.keycloak.x509.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-x509-secret
type: Opaque
stringData:
{{- with .Values.keycloak.x509.certificates }}
  {{- toYaml . | nindent 2 }}
{{- end -}}
{{- end -}}
