{{- range .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" $ }}-{{ .nameSuffix }}
  {{- with .annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
  {{- with .labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end -}}
