{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-headless
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
  {{- if $highAvailability }}
    - name: jgroups
      port: {{ .Values.keycloak.service.jgroupsPort }}
      targetPort: jgroups
      protocol: TCP
  {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
