{{- if and .Values.prometheus.operator.enabled -}}
{{- with .Values.prometheus.operator.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keycloak.fullname" $ }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
    {{- toYaml .selector | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: http
  endpoints:
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
      scrapeTimeout: {{ .scrapeTimeout }}
{{- end }}
{{- end -}}
