extraEnv: |
  - name: DB_VENDOR
    value: h2
  - name: KEYCLOAK_USER_FILE
    value: /secrets/admin-creds/user
  - name: KEYCLOAK_PASSWORD_FILE
    value: /secrets/admin-creds/password

secrets:
  - nameSuffix: admin-creds
    stringData:
      user: admin
      password: secret

extraVolumeMounts: |
  - name: admin-creds
    mountPath: "/secrets/admin-creds"
    readOnly: true

extraVolumes: |
  - name: admin-creds
    secret:
      secretName: '{{ include "keycloak.fullname" . }}-admin-creds'

postgresql:
  enabled: false

test:
  enabled: true
