replicas: 2

podLabels:
  test-label: test-label-value

podAnnotations:
  test-annotation: test-annotation-value-{{ .Release.Name }}
  test-int-annotation: "12345"

startupScripts:
  hello.sh: |
    #!/bin/sh

    echo '********************************************************************************'
    echo '*                                                                              *'
    echo '*                        Hello from my startup script!                         *'
    echo '*                                                                              *'
    echo '********************************************************************************'

lifecycleHooks: |
  postStart:
    exec:
      command:
        - /bin/sh
        - -c
        - echo 'Hello from lifecycle hook!'

extraEnv:
  JGROUPS_DISCOVERY_PROTOCOL: dns.DNS_PING
  JGROUPS_DISCOVERY_PROPERTIES: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
  CACHE_OWNERS_COUNT: "2"
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: "2"
  KEYCLOAK_USER_FILE: /secrets/admin-creds/user
  KEYCLOAK_PASSWORD_FILE: /secrets/admin-creds/password
  KEYCLOAK_STATISTICS: all
  JAVA_OPTS: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true

secrets:
  admin-creds:
    stringData:
      user: admin
      password: secret

extraVolumeMounts: |
  - name: admin-creds
    mountPath: /secrets/admin-creds
    readOnly: true

extraVolumes: |
  - name: admin-creds
    secret:
      secretName: '{{ include "keycloak.fullname" . }}-admin-creds'

postgresql:
  enabled: true
  persistence:
    enabled: true

test:
  enabled: true
