name: _Release chart template
on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.Bump.outputs.publish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Bump
        id: Bump
        run: |
            git pull
            pip install bump2version
            python scripts/bump-version.py ${{ inputs.chart }}
            git push
  upload:
    runs-on: ubuntu-latest
    needs:
      - bump-version
    if: needs.bump-version.outputs.publish == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
