{{- range .Values.referenceContent }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.fullname" $ }}-{{ include "jenkins.configmapSuffix" . }}
  labels:
    {{- include "jenkins.masterLabels" $ | nindent 4 }}
data:
{{- range required "Reference content item needs .data" .data }}
  {{ required "Reference content .data item needs .fileName" .fileName }}: |
    {{- tpl (required "Reference content .data item needs .fileContent" .fileContent) $ | nindent 4 }}
{{- end }}
{{- end }}
