apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.fullname" . }}-init
  labels:
    {{- include "jenkins.masterLabels" . | nindent 4 }}
data:
  init.sh: |
    {{- .Files.Get "scripts/init.sh" | nindent 4 }}
