{{- if and (not .Values.casc.existingSecret) .Values.casc.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.cascSecret" . }}
  labels:
    {{- include "jenkins.masterLabels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.casc.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end -}}
