{{- $context := dict "Values" $.Values "Chart" $.Chart "Release" $.Release }}
{{- range $key, $value := .Values.serviceAccount }}
  {{- $_ := set $context "fullname" (printf "%s-%s" (include "jenkins.fullname" $) $key) }}
  {{- $_ := set $context "name" $key }}
  {{- $_ := set $context "create" .create }}
  {{- $_ := set $context "resourceName" .name }}

  {{- with $value }}
    {{- if .create }}
      {{- print "---" | nindent 0 }}
      {{- include "jenkins.serviceAccount" $context | nindent 0 }}
    {{- end }}
  {{- end }}
{{- end }}
