apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-agent
  labels:
    {{- include "jenkins.masterLabels" . | nindent 4 }}
  {{- with .Values.service.agent.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service.agent.clusterIP }}
    clusterIP: "{{ . }}"
  {{- end }}
  ports:
    - port: {{ .Values.service.agent.port }}
      targetPort: agent
      protocol: TCP
      name: agent
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
